config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sign-up', as: 'sign-up', to: 'users#new'
  # get '/', to: "items#index"
  root "welcome#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  put '/cart', to: "carts#update"
  delete '/cart', to: "carts#destroy"
  get '/cart', to: "carts#show"
  post '/cart', to: "carts#create"

  get '/dashboard', to: 'users#show', as: "dashboard"
  resources :users, only: [:new, :create, :edit, :update ]

  resources :items, only: [:index, :show]

  resources :orders, only: [:index, :show, :create]

  namespace :admin do
    get 'dashboard', to: "dashboard#index"
    get 'analytics-dashboard', to: "analytics#index"
    resources :items
    resources :orders, only: [:update]
  end

  resources :categories, only: [ :index]
  get "/:category", to: "categories#show", as: "category"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def index
    @orders_by_status = Order.all.group(:status).count
    @statuses = Order.statuses

    if !params[:filter].nil?
      @orders = Order.where("status = #{params[:filter]}").order("id ASC").paginate(:page => params[:page], :per_page => 30)
    else
      @orders = Order.all.order("id ASC").paginate(:page => params[:page], :per_page => 15)
    end
  end

end

app/views/admin/dashboard/index.html.erb
<div class="dashboard">
  <div class="dashboard-info">
    <div class="dashboard-info-box">
      <h1>Admin Dashboard</h1>
      <%= link_to "View Your Items", admin_items_path %><br>
      <%= link_to "Analytics Dashboard", admin_analytics_dashboard_path %>
    </div>
    <div class="dashboard-info-box">
      <h2>Orders by Status</h2>
      <table>
        <th>Status</th>
        <th>Count of Orders</th>
        <% @orders_by_status.each do |status, count| %>
        <tr>
          <td><%= status %></td>
          <td><%= count %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="dashboard-orders">
    <h2>Orders</h2>
    <%= form_tag admin_dashboard_path, method: :get do %>
      <%= label_tag "Filter" %>
      <%= select_tag :filter, options_for_select(@statuses, params[:filter]) %>
      <%= submit_tag "Apply" %>
    <% end %>
    <table class="all-orders">
      <th>Order ID</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <% @orders.each do |order| %>
      <tr id=<%= order.id %>>
          <td><%= link_to order.id, order_path(order) %></td>
          <td><%= order.status %></td>
        <% if order.status == "Ordered" %>
          <td><%= button_to "mark as paid", admin_order_path(order, status: "Paid", filter: params[:filter]), method: :put%></td>
          <td><%= button_to "cancel", admin_order_path(order, status: "Cancelled", filter: params[:filter]), method: :put %></td>
        <% elsif order.status == "Paid" %>
          <td><%= button_to "mark as completed", admin_order_path(order, status: "Completed", filter: params[:filter]), method: :put%></td>
          <td><%= button_to "cancel", admin_order_path(order, status: "Cancelled", filter: params[:filter]), method: :put %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
      <% end %>
    </table>
    <div class="paginate-container">
      <%= will_paginate @orders %>
    </div>
  </div>
</div>