config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sign-up', as: 'sign-up', to: 'users#new'
  # get '/', to: "items#index"
  root "welcome#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  put '/cart', to: "carts#update"
  delete '/cart', to: "carts#destroy"
  get '/cart', to: "carts#show"
  post '/cart', to: "carts#create"

  get '/dashboard', to: 'users#show', as: "dashboard"
  resources :users, only: [:new, :create, :edit, :update ]

  resources :items, only: [:index, :show]

  resources :orders, only: [:index, :show, :create]

  namespace :admin do
    get 'dashboard', to: "dashboard#index"
    get 'analytics-dashboard', to: "analytics#index"
    resources :items
    resources :orders, only: [:update]
  end

  resources :categories, only: [ :index]
  get "/:category", to: "categories#show", as: "category"
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    @contents = contents || Hash.new(0)
  end

  def items
    contents.keys
  end

  def total_count
    contents.values.sum
  end

  def count_of(id)
    contents[id.to_s]
  end

  def add_item(id)
    contents[id.to_s] = 0 if contents[id.to_s].nil?
    contents[id.to_s] += 1
  end

  def remove_item(id)
    contents.delete(id.to_s)
  end

  def item_subtotal(price, id)
    price * count_of(id).to_i
  end

  def adjust_item(id, quantity)
    contents[id.to_s] = quantity.to_i
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper
  helper_method :cart_total_price

  def show
    @items = @cart.items.map {|item|Item.find(item.to_i)}
  end


  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    flash.notice = "You now have #{pluralize(@cart.count_of(item.id), item.title)} in your cart!"
    redirect_to cart_path
  end

  def update
    item = Item.find(params[:item_id])
    @cart.adjust_item(params[:item_id], params[:item][:quantity])
    session[:cart] = @cart.contents
    flash.notice = "You now have #{pluralize(@cart.count_of(item.id), item.title)} in your cart!"
    redirect_to cart_path
  end

  def destroy
    item = Item.find(params[:item_id])
    @cart.remove_item(item.id)
    session[:cart] = @cart.contents
    flash.notice = "Successfully removed #{view_context.link_to(item.title,item_path(item))} from your cart.".html_safe
    redirect_to cart_path
  end

  def cart_total_price
    @cart.contents.map { |key, value| Item.find(key.to_i).price * value.to_i }.sum
  end
end

app/views/carts/_contents.html.erb
<table class="cart-contents">
    <th>Knit</th>
    <th></th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th></th>
  <% @items.each do |item| %>
  <tr>
    <td class="product-card-thumbnail">
      <%= link_to image_tag(asset_path(item.image)), item_path(item)  %>
    </td>
    <td><h4><%= link_to "#{item.title}", item_path(item) %></h4><%= item.description %></td>
    <td class="cart-item-price"><%= item.price_in_dollars %></td>
    <td class="cart-item-quantity">
      <%= form_for item, {method: :put, url: cart_path(item_id: item.id)} do |f| %>
        <%= f.number_field :quantity,
                           {value: @cart.count_of(item.id),
                            min: 0,
                            class: "update"} %><br/>
        <%= f.submit "Update" %>
      <% end %>
    </td>
    <td class="cart-item-subtotal"><%= price_in_dollars(@cart.item_subtotal(item.price, item.id)) %></td>
    <td><%= button_to "Remove", cart_path(item_id: item.id), method: :delete %> </td>
  </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td class="cart-item-total">Knit Total Cost:</td>
    <td class="cart-item-total"><%= number_to_currency(cart_total_price/100) %></td>
  </tr>
</table>

<% if logged_in? %>
  <%= link_to "Checkout", orders_path, :method => 'post' %>
<% else %>
  <%= link_to "Login or Create Account to Checkout", login_path %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <h2>Shopping Cart</h2>
  <% if !@cart.contents.empty? %>
    <%= render partial: "contents" %>
  <% else %>
    <p>Your cart is currently Empty</p>
    <p>Continue Shopping <%= link_to "here", items_path %></p>
  <% end %>
</div>