config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sign-up', as: 'sign-up', to: 'users#new'
  # get '/', to: "items#index"
  root "welcome#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  put '/cart', to: "carts#update"
  delete '/cart', to: "carts#destroy"
  get '/cart', to: "carts#show"
  post '/cart', to: "carts#create"

  get '/dashboard', to: 'users#show', as: "dashboard"
  resources :users, only: [:new, :create, :edit, :update ]

  resources :items, only: [:index, :show]

  resources :orders, only: [:index, :show, :create]

  namespace :admin do
    get 'dashboard', to: "dashboard#index"
    get 'analytics-dashboard', to: "analytics#index"
    resources :items
    resources :orders, only: [:update]
  end

  resources :categories, only: [ :index]
  get "/:category", to: "categories#show", as: "category"
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :retired_items
  has_many :item_categories
  has_many :categories, through: :item_categories
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :title, :status, :description, :price
  validates :price, numericality: { greater_than: 0 }
  validates :title, uniqueness: true
  after_update :retire_item

  enum status: [:retired, :active, :out_of_stock]

  def price_in_dollars
    "$#{sprintf('%.2f', price/100)}"
  end

  def active?
    status == "active"
  end

  def retired?
    status == "retired"
  end

  def out_of_stock?
    status == "out_of_stock"
  end

  def times_retired
    retired_items.length
  end

  def self.categories_with_highest_price
    order("price DESC").first.categories
  end

  def self.retired_items
    select('items.*, count(retired_items.item_id) as retired_count')
    .joins(:retired_items)
    .group('items.id')
    .order('retired_count DESC')
  end

  def self.sort(sort)
    sort = "title ASC" if sort.nil?
    all
    .order(sort)
  end

  private

    def retire_item
      if self.status == "retired"
        RetiredItem.create(item: self)
      end
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  helper_method :item_status_filter

  def index
    if params[:filter].nil? || params[:filter] == "all"
      @items = Item.sort(params[:sort])
    else
      @items = Item.sort(params[:sort]).where(status: params[:filter])
    end
    @category =Category.all
  end

  def show
    redirect_to admin_items_path
  end

  def new
    @item = Item.new
    @category = Category.all
  end

  def create
    @item =Item.new(item_attributes)
    if item_params[:image].nil? && @item.save
      @item.update_column(:image, "app/assets/images/item_default.jpg")
      redirect_to admin_items_path
    elsif @item.save
      redirect_to admin_items_path
    else
      flash.notice = "Invalid Attributes, Make Sure Item Attributes are Valid"
      redirect_to new_admin_item_path
    end
  end

  def edit
    @category = Category.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if params[:status]
      @item.update(status: params[:status])
      flash[:success] = "Item Status Updated to #{@item.status}!"
      redirect_to admin_items_path
    else
      @item.update(item_attributes)
      flash[:success] = "Item Updated!"
      redirect_to admin_items_path
    end
  end

  def destroy
    @item= Items.find(params[:id])
    @item.destroy
      flash[:success] = "item deleted!"
      redirect_to admin_items_path
  end

private

  def item_status_filter
    [
      ["All", "all"],
      ["Retired", "retired"],
      ["Active", "active"]
    ]
  end

  def item_params
    params.require(:item).permit(:title,:description, :price, :image, {:categories => []}, :status)
  end

  def item_categories(item_params)
    categories = item_params[:categories]
    categories.reduce([]) do |results, category|
      if category != ""
        results << Category.find(category)
      end
      results
    end
  end

  def item_attributes
    item_attributes = item_params
    item_attributes[:categories] = item_categories(item_params) if item_params[:categories]
    item_attributes
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.sort(params[:sort]).paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/views/items/index.html.erb
<% if @category %>
<h3><%= link_to "Categories", categories_path %> > <%= @category.name.capitalize %></h3>
<% else %>
<h3>All Knits</h3>
<% end %>

<div class="sort">
  <%= form_tag(items_path, method: :get) do %>
    <%= select_tag(:sort, options_for_select(item_sort, params[:sort])) %>
    <%= submit_tag "Sort" %>
  <% end %>
</div>

<div class="all-items">
<% @items.each_with_index do |item, index| %>
  <div class="product-card" id=<%= index %>>
    <div class="product-card-thumbnail">
      <%= link_to image_tag(asset_path(item.image)), item_path(item)  %>
    </div>
    <%= link_to item.title, item_path(item), class: "product-card-title" %></br>
    <span class="product-card-price"><%= item.price_in_dollars %></span></br>
    <%= button_to "Add to Cart", cart_path(item_id: item.id), :disabled => !item.active? %>
  </div>
<% end %>
</div>

<div class="paginate-container">
  <%= will_paginate @items %>
</div>

app/views/items/show.html.erb
<div class="product-page">
  <div class="product-image">
    <img src='<%= asset_path(@item.image) %>'>
  </div>
  <div class="product-details">
    <h2><%= @item.title %></h2>
    <h3><%= @item.price_in_dollars %></h3>
    <% if @item.active? %>
    <%= button_to "Add to Cart", cart_path(item_id: @item.id) %>
    <% elsif @item.retired? %>
      <p>Item Retired</p>
    <% elsif @item.out_of_stock? %>
      <p>Out of Stock</p>
    <% end %>
    <p><%= @item.description %></p>
  </div>
</div>