config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sign-up', as: 'sign-up', to: 'users#new'
  # get '/', to: "items#index"
  root "welcome#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  put '/cart', to: "carts#update"
  delete '/cart', to: "carts#destroy"
  get '/cart', to: "carts#show"
  post '/cart', to: "carts#create"

  get '/dashboard', to: 'users#show', as: "dashboard"
  resources :users, only: [:new, :create, :edit, :update ]

  resources :items, only: [:index, :show]

  resources :orders, only: [:index, :show, :create]

  namespace :admin do
    get 'dashboard', to: "dashboard#index"
    get 'analytics-dashboard', to: "analytics#index"
    resources :items
    resources :orders, only: [:update]
  end

  resources :categories, only: [ :index]
  get "/:category", to: "categories#show", as: "category"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-profile max">
    <h3>Max Stackhouse</h3>
    <a href="https://github.com/Maxscores" id="max-github" class="social-links"><i class="fa fa-github" aria-hidden="true"></i></a>
  </div>
  <div class="footer-profile zach">
    <h3>Zach Landes</h3>
    <a href="https://github.com/zacharylandes" id="zach-github" class="social-links"><i class="fa fa-github" aria-hidden="true"></i></a>
  </div>
  <div class="footer-profile katy">
    <h3>Katy Welyczko</h3>
    <a href="https://github.com/katyjane8" id="katy-github" class="social-links"><i class="fa fa-github" aria-hidden="true"></i></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
  <%= link_to image_tag(asset_path("knitwits.png")), root_path  %>

    <ul class="menu menu-hover-lines">
      <li><%= link_to 'Home', root_path  %></li>
      <li><%= link_to 'Knits', items_path  %></li>
      <li><%= link_to 'Categories', categories_path  %></li>
      <li><%= link_to cart_path do %>


        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <%= @cart.total_count %>
        <% end %></li>
        <% if current_admin? && logged_in? %>
        <li><%= link_to "Dashboard", admin_dashboard_path %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% elsif logged_in? %>
        <li><%= link_to "Account", dashboard_path %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
</nav>
<% if current_user %>
<div class="nav-logged-in">
  <p>Logged in as <%= current_user.username %> (<%= link_to "Edit Profile", edit_user_path(current_user) %>)</p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnitWits</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300" rel="stylesheet"> -->
    <%= favicon_link_tag 'favicon-32x32.png' %>
</head>
  <body>
    <%= render partial: "layouts/header" %>

    <% flash.each do |type, message| %>
      <%= content_tag :div, message.html_safe, class: type %>
    <% end %>

    <div class="page">
      <%= yield %>
    </div>

 <%= render partial: "layouts/footer" %>
  </body>

</html>